using System.Text;

namespace FlowForge.Core.Export;

/// <summary>
/// Provides static string templates and formatting methods for C# code generation
/// from FlowForge workflows.
/// </summary>
public static class CodeTemplate
{
    /// <summary>
    /// Generates the file header comment block.
    /// </summary>
    public static string FileHeader(string workflowName, DateTime generatedDate)
    {
        return $"""
            // Generated by FlowForge
            // Workflow: "{workflowName}"
            // Generated: {generatedDate:yyyy-MM-dd}
            """;
    }

    /// <summary>
    /// Generates the using statements block.
    /// </summary>
    public static string UsingStatements()
    {
        return """
            using System.Net.Http;
            using System.Text.Json;
            """;
    }

    /// <summary>
    /// Generates the class declaration with HttpClient constructor.
    /// </summary>
    public static string ClassHeader(string className)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.Append("    }");
        return sb.ToString();
    }

    /// <summary>
    /// Generates the ExecuteAsync method signature.
    /// </summary>
    public static string MethodHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("    public async Task ExecuteAsync(CancellationToken ct = default)");
        sb.Append("    {");
        return sb.ToString();
    }

    /// <summary>
    /// Generates the method and class closing braces.
    /// </summary>
    public static string MethodAndClassFooter()
    {
        var sb = new StringBuilder();
        sb.AppendLine("    }");
        sb.Append("}");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a step comment line.
    /// </summary>
    public static string StepComment(int stepNumber, string description, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}// Step {stepNumber}: {description}";
    }

    /// <summary>
    /// Generates an HTTP GET request code block.
    /// </summary>
    public static string HttpGetRequest(string url, string variablePrefix = "response", int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}var {variablePrefix} = await _httpClient.GetAsync(\"{EscapeString(url)}\", ct);");
        sb.AppendLine($"{indent}var statusCode = (int){variablePrefix}.StatusCode;");
        sb.Append($"{indent}var body = await {variablePrefix}.Content.ReadAsStringAsync(ct);");
        return sb.ToString();
    }

    /// <summary>
    /// Generates an HTTP POST request code block.
    /// </summary>
    public static string HttpPostRequest(string url, string variablePrefix = "response", int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}var content = new StringContent(\"\", System.Text.Encoding.UTF8, \"application/json\");");
        sb.AppendLine($"{indent}var {variablePrefix} = await _httpClient.PostAsync(\"{EscapeString(url)}\", content, ct);");
        sb.AppendLine($"{indent}var statusCode = (int){variablePrefix}.StatusCode;");
        sb.Append($"{indent}var body = await {variablePrefix}.Content.ReadAsStringAsync(ct);");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a condition (if/else) opening block.
    /// </summary>
    public static string ConditionStart(string condition, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}if ({condition})";
    }

    /// <summary>
    /// Generates an opening brace at the given indent level.
    /// </summary>
    public static string OpenBrace(int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}{{";
    }

    /// <summary>
    /// Generates a closing brace at the given indent level.
    /// </summary>
    public static string CloseBrace(int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}}}";
    }

    /// <summary>
    /// Generates an else block opening.
    /// </summary>
    public static string ElseBlock(int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}else";
    }

    /// <summary>
    /// Generates a foreach loop opening.
    /// </summary>
    public static string ForEachStart(string variableName, string collection, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}foreach (var {variableName} in {collection})";
    }

    /// <summary>
    /// Generates a Console.WriteLine statement.
    /// </summary>
    public static string LogStatement(string message, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}Console.WriteLine($\"{EscapeString(message)}\");";
    }

    /// <summary>
    /// Generates a Task.Delay statement.
    /// </summary>
    public static string DelayStatement(int milliseconds, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}await Task.Delay({milliseconds}, ct);";
    }

    /// <summary>
    /// Generates a variable assignment statement.
    /// </summary>
    public static string VariableAssignment(string variableName, string value, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}var {SanitizeIdentifier(variableName)} = {value};";
    }

    /// <summary>
    /// Generates a TODO comment for features not yet implemented.
    /// </summary>
    public static string TodoComment(string feature, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        return $"{indent}// TODO: Implement {feature}";
    }

    /// <summary>
    /// Generates an inline code block from user-provided code.
    /// </summary>
    public static string InlineCode(string code, int indentLevel = 2)
    {
        if (string.IsNullOrWhiteSpace(code))
            return string.Empty;

        string indent = new(' ', indentLevel * 4);
        var lines = code.Split('\n');
        var sb = new StringBuilder();

        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i].TrimEnd('\r');
            if (i < lines.Length - 1)
                sb.AppendLine($"{indent}{line}");
            else
                sb.Append($"{indent}{line}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a transform / object mapping block.
    /// </summary>
    public static string TransformBlock(string expression, string variableName = "result", int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        if (string.IsNullOrWhiteSpace(expression))
            return $"{indent}var {SanitizeIdentifier(variableName)} = body; // TODO: Add transform expression";

        return $"{indent}var {SanitizeIdentifier(variableName)} = {expression};";
    }

    /// <summary>
    /// Generates a webhook entry point comment.
    /// </summary>
    public static string WebhookEntry(string path, string method, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}// Webhook endpoint: {method.ToUpperInvariant()} {path}");
        sb.Append($"{indent}// This method is triggered when the webhook is called");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a database query TODO comment block.
    /// </summary>
    public static string DatabaseQueryBlock(string query, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}// TODO: Implement database query");
        sb.Append($"{indent}// Query: {EscapeString(query)}");
        return sb.ToString();
    }

    /// <summary>
    /// Generates an email sending TODO comment block.
    /// </summary>
    public static string EmailBlock(string to, string subject, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}// TODO: Implement email sending");
        sb.AppendLine($"{indent}// To: {EscapeString(to)}");
        sb.Append($"{indent}// Subject: {EscapeString(subject)}");
        return sb.ToString();
    }

    /// <summary>
    /// Generates a retry loop block.
    /// </summary>
    public static string RetryBlock(int maxRetries, int delayMs, int indentLevel = 2)
    {
        string indent = new(' ', indentLevel * 4);
        var sb = new StringBuilder();
        sb.AppendLine($"{indent}for (int attempt = 1; attempt <= {maxRetries}; attempt++)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    try");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        // TODO: Place the operation to retry here");
        sb.AppendLine($"{indent}        break; // Success, exit retry loop");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    catch (Exception ex) when (attempt < {maxRetries})");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        Console.WriteLine($\"Attempt {{attempt}} failed: {{ex.Message}}. Retrying in {delayMs}ms...\");");
        sb.AppendLine($"{indent}        await Task.Delay({delayMs}, ct);");
        sb.AppendLine($"{indent}    }}");
        sb.Append($"{indent}}}");
        return sb.ToString();
    }

    /// <summary>
    /// Escapes special characters in a string for use in C# string literals.
    /// </summary>
    public static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;

        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    /// <summary>
    /// Sanitizes a string to be a valid C# identifier.
    /// </summary>
    public static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "value";

        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];
            if (i == 0 && char.IsDigit(c))
            {
                sb.Append('_');
            }
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                sb.Append(c);
            }
            else
            {
                sb.Append('_');
            }
        }

        string result = sb.ToString();
        return string.IsNullOrEmpty(result) ? "value" : result;
    }

    /// <summary>
    /// Converts a workflow name into a valid C# class name using PascalCase.
    /// </summary>
    public static string ToClassName(string workflowName)
    {
        if (string.IsNullOrWhiteSpace(workflowName))
            return "GeneratedWorkflow";

        var sb = new StringBuilder();
        bool capitalizeNext = true;

        foreach (char c in workflowName)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        string result = sb.ToString();
        if (result.Length == 0 || char.IsDigit(result[0]))
            return "GeneratedWorkflow";

        return result;
    }
}
