using FlowForge.Core.Export;
using FlowForge.Core.Models;
using FluentAssertions;

namespace FlowForge.Core.Tests.Export;

public class CSharpCodeGeneratorTests
{
    private readonly CSharpCodeGenerator _generator = new();

    [Fact]
    public void Format_ReturnsCSharp()
    {
        _generator.Format.Should().Be("csharp");
    }

    [Fact]
    public void Export_ContainsClassDeclaration()
    {
        // Arrange
        var workflow = CreateSimpleWorkflow("My Workflow");

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("public class MyWorkflow");
    }

    [Fact]
    public void Export_ContainsFileHeader()
    {
        // Arrange
        var workflow = CreateSimpleWorkflow("Test Pipeline");

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("Generated by FlowForge");
        code.Should().Contain("Test Pipeline");
    }

    [Fact]
    public void Export_ContainsUsingStatements()
    {
        // Arrange
        var workflow = CreateSimpleWorkflow("Test");

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("using System.Net.Http;");
        code.Should().Contain("using System.Text.Json;");
    }

    [Fact]
    public void Export_ContainsExecuteAsyncMethod()
    {
        // Arrange
        var workflow = CreateSimpleWorkflow("Test");

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("public async Task ExecuteAsync");
        code.Should().Contain("CancellationToken ct");
    }

    [Fact]
    public void Export_HttpRequestNode_GeneratesHttpCode()
    {
        // Arrange - use "httprequest" type (without hyphen) which the code generator recognizes
        var workflow = new Workflow
        {
            Metadata = new WorkflowMetadata { Name = "Http Test" },
            Nodes = new List<FlowNode>
            {
                new()
                {
                    Id = "http-1",
                    Type = "httprequest",
                    Name = "Fetch Data",
                    Config = new NodeConfig { ["url"] = "https://api.example.com/data", ["method"] = "GET" },
                    InputPorts = new List<NodePort>(),
                    OutputPorts = new List<NodePort> { new() { Name = "success", NodeId = "http-1" } }
                }
            },
            Edges = new List<FlowEdge>()
        };

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("GetAsync");
        code.Should().Contain("api.example.com");
    }

    [Fact]
    public void Export_LoggerNode_GeneratesConsoleWriteLine()
    {
        // Arrange
        var workflow = new Workflow
        {
            Metadata = new WorkflowMetadata { Name = "Logger Test" },
            Nodes = new List<FlowNode>
            {
                new()
                {
                    Id = "log-1",
                    Type = "logger",
                    Name = "Log Output",
                    Config = new NodeConfig { ["message"] = "Hello World" },
                    InputPorts = new List<NodePort>(),
                    OutputPorts = new List<NodePort> { new() { Name = "output", NodeId = "log-1" } }
                }
            },
            Edges = new List<FlowEdge>()
        };

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("Console.WriteLine");
        code.Should().Contain("Hello World");
    }

    [Fact]
    public void Export_ConditionNode_GeneratesIfElse()
    {
        // Arrange
        var condId = "cond-1";
        var trueId = "true-1";
        var falseId = "false-1";

        var workflow = new Workflow
        {
            Metadata = new WorkflowMetadata { Name = "Branch Test" },
            Nodes = new List<FlowNode>
            {
                new()
                {
                    Id = condId, Type = "condition", Name = "Check",
                    Config = new NodeConfig { ["expression"] = "statusCode == 200" },
                    InputPorts = new List<NodePort>(),
                    OutputPorts = new List<NodePort>
                    {
                        new() { Name = "true", NodeId = condId },
                        new() { Name = "false", NodeId = condId }
                    }
                },
                new()
                {
                    Id = trueId, Type = "logger", Name = "OK",
                    Config = new NodeConfig { ["message"] = "Success" },
                    InputPorts = new List<NodePort> { new() { Name = "input", NodeId = trueId } },
                    OutputPorts = new List<NodePort>()
                },
                new()
                {
                    Id = falseId, Type = "logger", Name = "Fail",
                    Config = new NodeConfig { ["message"] = "Error" },
                    InputPorts = new List<NodePort> { new() { Name = "input", NodeId = falseId } },
                    OutputPorts = new List<NodePort>()
                }
            },
            Edges = new List<FlowEdge>
            {
                new() { SourceNodeId = condId, SourcePortName = "true", TargetNodeId = trueId, TargetPortName = "input" },
                new() { SourceNodeId = condId, SourcePortName = "false", TargetNodeId = falseId, TargetPortName = "input" }
            }
        };

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("if (");
        code.Should().Contain("else");
    }

    [Fact]
    public void Export_DelayNode_GeneratesTaskDelay()
    {
        // Arrange
        var workflow = new Workflow
        {
            Metadata = new WorkflowMetadata { Name = "Delay Test" },
            Nodes = new List<FlowNode>
            {
                new()
                {
                    Id = "delay-1", Type = "delay", Name = "Wait",
                    Config = new NodeConfig { ["milliseconds"] = 2000 },
                    InputPorts = new List<NodePort>(),
                    OutputPorts = new List<NodePort> { new() { Name = "output", NodeId = "delay-1" } }
                }
            },
            Edges = new List<FlowEdge>()
        };

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("Task.Delay");
    }

    [Fact]
    public void Export_EmptyWorkflow_StillGeneratesValidStructure()
    {
        // Arrange
        var workflow = new Workflow
        {
            Metadata = new WorkflowMetadata { Name = "Empty" },
            Nodes = new List<FlowNode>(),
            Edges = new List<FlowEdge>()
        };

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("public class Empty");
        code.Should().Contain("public async Task ExecuteAsync");
    }

    [Fact]
    public void Export_ContainsStepComments()
    {
        // Arrange
        var workflow = CreateSimpleWorkflow("Step Test");

        // Act
        var code = _generator.Export(workflow);

        // Assert
        code.Should().Contain("// Step 1:");
    }

    private static Workflow CreateSimpleWorkflow(string name)
    {
        return new Workflow
        {
            Metadata = new WorkflowMetadata { Name = name },
            Nodes = new List<FlowNode>
            {
                new()
                {
                    Id = "n1", Type = "webhook-trigger", Name = "Start",
                    Config = new NodeConfig { ["path"] = "/webhook", ["method"] = "POST" },
                    InputPorts = new List<NodePort>(),
                    OutputPorts = new List<NodePort> { new() { Name = "output", NodeId = "n1" } }
                },
                new()
                {
                    Id = "n2", Type = "logger", Name = "End",
                    Config = new NodeConfig { ["message"] = "Done" },
                    InputPorts = new List<NodePort> { new() { Name = "input", NodeId = "n2" } },
                    OutputPorts = new List<NodePort>()
                }
            },
            Edges = new List<FlowEdge>
            {
                new() { SourceNodeId = "n1", SourcePortName = "output", TargetNodeId = "n2", TargetPortName = "input" }
            }
        };
    }
}
